# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NANA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NANA
    pod "PagingKit" # add

  target 'NANATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NANAUITests' do
    # Pods for testing
  end

end
